export const REGIONS: { code: number; name: string }[] = [
  { code: 0, name: "Riket" },
  { code: 1, name: "Stockholms län" },
  { code: 3, name: "Uppsala län" },
  { code: 4, name: "Södermanlands län" },
  { code: 5, name: "Östergötlands län" },
  { code: 6, name: "Jönköpings län" },
  { code: 7, name: "Kronobergs län" },
  { code: 8, name: "Kalmar län" },
  { code: 9, name: "Gotlands län" },
  { code: 10, name: "Blekinge län" },
  { code: 12, name: "Skåne län" },
  { code: 13, name: "Hallands län" },
  { code: 14, name: "Västra Götalands län" },
  { code: 17, name: "Värmlands län" },
  { code: 18, name: "Örebro län" },
  { code: 19, name: "Västmanlands län" },
  { code: 20, name: "Dalarnas län" },
  { code: 21, name: "Gävleborgs län" },
  { code: 22, name: "Västernorrlands län" },
  { code: 23, name: "Jämtlands län" },
  { code: 24, name: "Västerbottens län" },
  { code: 25, name: "Norrbottens län" },
]